---
title: "Generating input for MaxEnt grammar computation"
author: "SM (Version TK)"
date: "04.09.2023"
output: html_document
---

```{r libraries, warning = FALSE, message = FALSE}
library(tidyverse)

show(version)
```

### Reading in the data (EXP 1)

```{r data preparation exp_1}
item_data_exp_1 <- 
  read_csv("EXP 1 (INSTR, COMS, Interpretation)/Data/ForcedChoice_test.csv", 
           col_types = "fffiifffifffiii") %>%
  mutate(SENSE = factor(ifelse(INTEGRATION == "yes", "affirmative", "privative")),
         ADVERBIAL_TYPE = relevel(ADVERBIAL_TYPE, ref = "INSTR"))

```

### Constraints for EXP_1

Please note that the structural condition cannot be violated in EXP 1 because the antecedent is always the subject. TRUE marks constraint violation

```{r}

weight_computation_exp_1 <-
  item_data_exp_1 %>%
  mutate(structural_condition_str = "",
         agent_first = ifelse((ADVERBIAL_TYPE == "INSTR" | (ADVERBIAL_TYPE == "COM(S)" & 
                                                              SENSE == "privative") | 
                                 (ADVERBIAL_TYPE == "COM(S)" & SENSE == "affirmative" & 
                                    ANSWER == "PP>OBJ")), 
                              FALSE, TRUE),
         anim_first = ifelse((ADVERBIAL_TYPE == "INSTR" | (ADVERBIAL_TYPE == "COM(S)" & 
                                                             ANSWER == "PP>OBJ")), FALSE, TRUE),
         NP_first = ifelse(ANSWER == "OBJ>PP", FALSE, TRUE),
         agent_first_str = ifelse(agent_first, "1",""),
         anim_first_str = ifelse(anim_first, "1", ""),
         NP_first_str = ifelse(NP_first, "1", "")) %>%
  group_by(itemId, structural_condition_str, agent_first_str, anim_first_str, NP_first_str, ANSWER) %>%
  summarise(count = n()) %>%
  relocate(itemId, ANSWER, count) %>%
  as.data.frame()
  
options(width = 300)
weight_computation_exp_1
```

### Reading in data from EXP 2

```{r data preparation EXP 2}
item_data_exp_2 <- 
  read.csv("EXP 2 (INSTR, COMO, WH)/Data/EXP_2_test.csv", stringsAsFactors = TRUE) %>%
  rename(itemId = ITEM_ID) %>%
  select(-c(ITEM_FUNCTION, ITEM_SUBGROUP, comment, OPTION_0_ITEM, OPTION_1_ITEM, 
            date_time_begin, date_time_end))



```

### Constraints for EXP 2

Agent first is always met, because neither ADV is an agent. Also, anim_first is always met.

```{r}

weight_computation_exp_2 <-
  item_data_exp_2 %>%
  mutate(agent_first_str = "",
         anim_first_str = "",
         NP_first = ifelse(ANSWER == "OBJ>PP", FALSE, TRUE),
         structural_condition = ifelse((ANSWER == "PP>OBJ" & TYPE == "COM(O)"), TRUE, FALSE),
         NP_first_str = ifelse(NP_first, "1", ""),
         structural_condition_str = ifelse(structural_condition, "1", "")) %>%
  group_by(itemId, structural_condition_str, agent_first_str, anim_first_str, NP_first_str, ANSWER) %>%
  summarise(count = n()) %>%
  relocate(itemId, ANSWER, count) %>%
  as.data.frame()

options(width = 300)
weight_computation_exp_2

weight_computation <- rbind(weight_computation_exp_1, weight_computation_exp_2)
```

```{r}

write_tsv(weight_computation, "input_for_maxent_solver_exprep.csv")

write_tsv(head(weight_computation, 12), "test")


```